### ISSUE TITLE
Campo WEB não reconhecido em build's do Tuinity

### ISSUE THREAD

**Issue by TheMartinfer22** [HenryFabio/inventory-api#4]
O erro está na linha **51** do https://github.com/HenryFabio/inventory-api/blob/main/src/main/java/com/henryfabio/minecraft/inventoryapi/item/enums/DefaultItem.java

Build de servidor: **Tuinity**
Versão: **1.16.5**

Crash ao abrir o inventário:

```
[15:09:06 ERROR]: Could not pass event InventoryClickEvent to NextEconomy v2.0.3
java.lang.NoSuchFieldError: WEB
	at com.nextplugins.economy.libs.inventoryapi.item.enums.DefaultItem.lambda$static$5(DefaultItem.java:51) ~[?:?]
	at com.nextplugins.economy.libs.inventoryapi.item.enums.DefaultItem.toInventoryItem(DefaultItem.java:94) ~[?:?]
	at com.nextplugins.economy.libs.inventoryapi.viewer.impl.paged.PagedViewer.insertPageItems(PagedViewer.java:65) ~[?:?]
	at com.nextplugins.economy.libs.inventoryapi.inventory.impl.paged.PagedInventory.update(PagedInventory.java:55) ~[?:?]
	at com.nextplugins.economy.libs.inventoryapi.inventory.impl.CustomInventoryImpl.defaultOpenInventory(CustomInventoryImpl.java:77) ~[?:?]
	at com.nextplugins.economy.libs.inventoryapi.inventory.impl.paged.PagedInventory.openInventory(PagedInventory.java:28) ~[?:?]
	at com.nextplugins.economy.libs.inventoryapi.inventory.impl.CustomInventoryImpl.openInventory(CustomInventoryImpl.java:43) ~[?:?]
	at com.nextplugins.economy.views.button.model.ButtonType.lambda$static$3(ButtonType.java:33) ~[?:?]
	at com.nextplugins.economy.libs.inventoryapi.listener.CustomInventoryListener.lambda$onInventoryClick$0(CustomInventoryListener.java:54) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at com.nextplugins.economy.libs.inventoryapi.listener.CustomInventoryListener.onInventoryClick(CustomInventoryListener.java:40) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2797) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"935b901"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by TheMartinfer22** [comment]
Foi corrigido no #3
